server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:\app\work\local-repo
        git:
#          uri: file://D:\app\work\git-local-repo
          uri: https://github.com/ssun46/spring-cloud-config
#          username: username
#          password: password
          default-label: master
